name: DevOps lab

on:
  push:

jobs:
  linux-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Display hostname
        run: hostname

      - name: Display current directory
        run: pwd

      - name: Display files
        run: ls -la

      - name: Show date
        run: date
